# Generated by Django 5.2.6 on 2026-08-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BRERule',
        ),
    ]
