# Generated by Django 5.2.6 on 2026-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_delete_brerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRERule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'BRERule',
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
