# Generated by Django 5.2.6 on 2026-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_brerule_alter_lead_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
